name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # フロントエンドのテスト
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/front

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Lint check
      run: bun run lint

    - name: Format check
      run: bun run format

    - name: Build check
      run: bun run build

  # バックエンドのテスト
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run typecheck

    - name: Build check
      run: bun run build

  # ルートレベルのテスト
  root:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Verify monorepo structure
      run: |
        echo "Verifying monorepo structure..."
        ls -la apps/
        echo "Frontend package.json:"
        cat apps/front/package.json | grep '"name"'
        echo "Backend package.json:"
        cat apps/backend/package.json | grep '"name"'
