name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Clear npm cache and reinstall Biome
      run: npm cache clean --force && npm install @biomejs/biome@^1.9.4

    - name: Verify Biome installation
      run: npx @biomejs/biome --version

    - name: Type check
      run: npm run typecheck

    - name: Lint check
      run: npm run lint

    - name: Format check
      run: npm run format

    - name: Build check
      run: npm run build
